//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLog
    {
        public long LogId { get; set; }
        public string SourceApp { get; set; }
        public string DestinationApp { get; set; }
        public string RequestUrl { get; set; }
        public string Method { get; set; }
        public string RequestData { get; set; }
        public string ResponseData { get; set; }
        public int ResponseCode { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
