//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSBrandInShop
    {
        public int CMSBrandInShopId { get; set; }
        public Nullable<int> CMSId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandNameEN { get; set; }
        public string BrandNameTH { get; set; }
        public string Path { get; set; }
        public string PicUrl { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKey { get; set; }
        public string UrlKey { get; set; }
        public string ShortDescriptionEn { get; set; }
        public string LongDescriptionEn { get; set; }
        public string ShortDescriptionTh { get; set; }
        public string LongDescriptionTh { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateIP { get; set; }
        public string UpdateIP { get; set; }
    }
}
