//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSMasterSchedulerShopMap
    {
        public int CMSMasterSchedulerShopMapId { get; set; }
        public Nullable<int> CMSMasterSchedulerMapId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<bool> IsSendAlertToShop { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsJoinCampaign { get; set; }
        public Nullable<int> JoinTotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateIP { get; set; }
        public string UpdateIP { get; set; }
    }
}
