//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMSMaster
    {
        public int CMSMasterId { get; set; }
        public string CMSMasterNameEN { get; set; }
        public string CMSMasterNameTH { get; set; }
        public string CMSMasterURLKey { get; set; }
        public string CMSMasterType { get; set; }
        public Nullable<System.DateTime> CMSMasterEffectiveDate { get; set; }
        public Nullable<System.DateTime> CMSMasterExpireDate { get; set; }
        public int CMSMasterTotal { get; set; }
        public string MobileShortDescriptionTH { get; set; }
        public string MobileLongDescriptionTH { get; set; }
        public string ShortDescriptionTH { get; set; }
        public string LongDescriptionTH { get; set; }
        public string MobileShortDescriptionEN { get; set; }
        public string MobileLongDescriptionEN { get; set; }
        public Nullable<int> SortById { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string LongDescriptionEN { get; set; }
        public string LinkToOutside { get; set; }
        public bool IsCampaign { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public string FeatureTitle { get; set; }
        public bool TitleShowcase { get; set; }
        public string Status { get; set; }
        public bool Visibility { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string CreateIP { get; set; }
        public string UpdateIP { get; set; }
    }
}
