//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryLeadTime
    {
        public string ShipDistrict { get; set; }
        public string ShipAmphur { get; set; }
        public string ShipProvince { get; set; }
        public string ShipZipCode { get; set; }
        public int DeliveryLeadTime1 { get; set; }
    }
}
