//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalCategoryPID
    {
        public int CategoryId { get; set; }
        public string CategoryAbbreviation { get; set; }
        public string CurrentKey { get; set; }
    
        public virtual GlobalCategory GlobalCategory { get; set; }
    }
}
