//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public string GuestId { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public string TelephoneNo { get; set; }
        public byte Gender { get; set; }
        public bool ReceiveSms { get; set; }
        public string T1CNo { get; set; }
        public string CustTaxID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public int DistrictId { get; set; }
        public int PostCodeId { get; set; }
        public string BranchID { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public string BillFirstName { get; set; }
        public string BillLastName { get; set; }
        public string BillMobile { get; set; }
        public string BillTelephoneNo { get; set; }
        public Nullable<byte> BillGender { get; set; }
        public string BillAddressLine1 { get; set; }
        public string BillAddressLine2 { get; set; }
        public Nullable<int> BillProvinceId { get; set; }
        public Nullable<int> BillCityId { get; set; }
        public Nullable<int> BillDistrictId { get; set; }
        public Nullable<int> BillPostCodeId { get; set; }
        public string BillEmail { get; set; }
        public bool IsShipping { get; set; }
        public bool IsBilling { get; set; }
    }
}
