//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportHeader
    {
        public int ImportHeaderId { get; set; }
        public string HeaderName { get; set; }
        public string Description { get; set; }
        public string AcceptedValue { get; set; }
        public string Example { get; set; }
        public string Note { get; set; }
        public string GroupName { get; set; }
        public string MapName { get; set; }
    }
}
