//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryHistory
    {
        public int InventoryHistoryId { get; set; }
        public string Pid { get; set; }
        public int Quantity { get; set; }
        public int Defect { get; set; }
        public int OnHold { get; set; }
        public int Reserve { get; set; }
        public int MaxQtyPreOrder { get; set; }
        public bool UseDecimal { get; set; }
        public int SafetyStockSeller { get; set; }
        public int SafetyStockAdmin { get; set; }
        public int StockType { get; set; }
        public int MinQtyAllowInCart { get; set; }
        public int MaxQtyAllowInCart { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
