//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBProduct
    {
        public int ProductId { get; set; }
        public string PID { get; set; }
        public string NewPID { get; set; }
        public int ProductGroupId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameEN { get; set; }
        public string DocName { get; set; }
        public string DocNameEN { get; set; }
        public string UrlName { get; set; }
        public string UrlNameEN { get; set; }
        public Nullable<decimal> FullPrice { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitPriceIncVat { get; set; }
        public decimal PromotionPrice { get; set; }
        public int StockOnHand { get; set; }
        public int OnlineReserve { get; set; }
        public int StockAvar { get; set; }
        public int OnHold { get; set; }
        public int OnPO { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Description { get; set; }
        public string DescriptionEN { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string Review { get; set; }
        public string ReviewEN { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public bool NotReturnable { get; set; }
        public Nullable<byte> IsDeliveryByBU { get; set; }
        public string VirtualPath { get; set; }
        public bool IsPromotion { get; set; }
        public bool IsSale { get; set; }
        public string SaleUnit { get; set; }
        public string SaleUnitEN { get; set; }
        public decimal DeliverFeeItem { get; set; }
        public bool IsVat { get; set; }
        public bool IsDeal { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public bool OnlyCentral { get; set; }
        public bool NewArrival { get; set; }
        public bool OnlineEx { get; set; }
        public string DType { get; set; }
        public bool IsBestDeal { get; set; }
        public bool IsFree { get; set; }
        public string BU_SKU { get; set; }
        public string PidOD { get; set; }
        public string WorkingRemark { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createon { get; set; }
        public string updateby { get; set; }
        public Nullable<System.DateTime> updateon { get; set; }
        public string IDept { get; set; }
        public string DeptName { get; set; }
        public string ISDept { get; set; }
        public string SubDeptName { get; set; }
        public string IClass { get; set; }
        public string ClassName { get; set; }
        public string ISClass { get; set; }
        public string SubClassName { get; set; }
        public string Color_CDS { get; set; }
        public string Size_CDS { get; set; }
        public string WorkingStatus { get; set; }
        public int NumOfImage { get; set; }
        public string PromotionDescriptionTh { get; set; }
        public string PromotionDescriptionEn { get; set; }
        public Nullable<System.DateTime> PromotionExpiredDate { get; set; }
        public int SortGroup { get; set; }
        public int SortValue { get; set; }
        public System.DateTime LastSaleDate { get; set; }
        public string LocationId { get; set; }
        public int StockHold { get; set; }
        public string TranferBy { get; set; }
        public System.DateTime TranferDate { get; set; }
        public Nullable<System.DateTime> FirstDateHasStock { get; set; }
        public int FirstStockAvar { get; set; }
        public string TextIconPromotion { get; set; }
        public string TextIconPromotionEN { get; set; }
        public Nullable<System.DateTime> FirstDateOnWeb { get; set; }
        public int OnlineStockAvar { get; set; }
        public int SOReserve { get; set; }
        public string ISBN { get; set; }
        public string Keyword { get; set; }
        public string KeywordEN { get; set; }
        public string AboutProduct { get; set; }
        public string AboutProductEN { get; set; }
        public string Author { get; set; }
        public string AuthorEN { get; set; }
        public string TagLines { get; set; }
        public string TagLinesEN { get; set; }
    }
}
