//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBProductGroup
    {
        public int ProductGroupId { get; set; }
        public string DisplayName { get; set; }
        public string DisplayNameEN { get; set; }
        public int DepartmentId { get; set; }
        public string UrlName { get; set; }
        public int ProductGroupId_CDS { get; set; }
        public int Catlv3ID { get; set; }
        public int Catlv2ID { get; set; }
        public Nullable<int> ProductGroupID_REF { get; set; }
        public int CustomDepartmentId { get; set; }
    }
}
