//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBProductMaster
    {
        public int ProductId { get; set; }
        public int ProductGroupId { get; set; }
        public int DeptId { get; set; }
        public Nullable<int> PID { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Name { get; set; }
        public string Barcode { get; set; }
        public string NameEN { get; set; }
        public string OnlyCentral { get; set; }
        public string NewArrival { get; set; }
        public string OnlineEx { get; set; }
        public string FullName { get; set; }
        public string FullNameEn { get; set; }
        public string BrandName { get; set; }
        public string BrandNameEng { get; set; }
        public string DeptName { get; set; }
        public string DeptNameEng { get; set; }
        public string CatId { get; set; }
        public string SubCatId { get; set; }
        public string Class { get; set; }
        public string SubClass { get; set; }
        public Nullable<float> StdPrice { get; set; }
        public Nullable<float> SalePrice { get; set; }
        public Nullable<int> PromotionPrice { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string LongDescription { get; set; }
        public string LongDescriptionEN { get; set; }
        public string Status { get; set; }
        public string SaleUnit { get; set; }
        public string SaleUnitEN { get; set; }
        public Nullable<int> StockOnHand { get; set; }
        public Nullable<int> StockAvar { get; set; }
        public int DeliveryFee { get; set; }
        public int IsVat { get; set; }
        public int VatRate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string ProImg_CDS { get; set; }
        public string ParImgA_CDS { get; set; }
        public string ParImgB_CDS { get; set; }
        public string ParImgC_CDS { get; set; }
        public string ParImgD_CDS { get; set; }
        public string BrandId_CDS { get; set; }
    }
}
