//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBProductPicture
    {
        public int PictureId { get; set; }
        public int ProductId { get; set; }
        public string PictureSmallName { get; set; }
        public string PictureMediumName { get; set; }
        public string PictureLargeName { get; set; }
        public string Description { get; set; }
        public string DescriptionEN { get; set; }
    }
}
