//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBProductApproved
    {
        public string PID { get; set; }
        public bool IsSetGroup { get; set; }
        public bool IsSetBrand { get; set; }
        public bool IsSetDescription { get; set; }
        public bool IsSetUrl { get; set; }
        public bool IsSetImage { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public bool IsSetDescriptionEN { get; set; }
        public bool IsSetPhysical { get; set; }
        public string ResponsibleBy { get; set; }
        public Nullable<System.DateTime> JobAssignedDate { get; set; }
    }
}
