//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrate_TBPropertyCategory
    {
        public int PropCatId { get; set; }
        public int PropertyGroupId { get; set; }
        public string PropCatName { get; set; }
        public int SeqNo { get; set; }
    }
}
