//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODMProcessLog
    {
        public int LogID { get; set; }
        public string OrderID { get; set; }
        public string ProcessRemark { get; set; }
        public string Remark { get; set; }
        public string IPAddress { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
