//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODMPermission
    {
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
    }
}
