
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Colsp.Entity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ODMUserMenuItem
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public Nullable<int> Parent { get; set; }

    public System.DateTime CreateOn { get; set; }

    public string CreateBy { get; set; }

    public int Seq { get; set; }

    public string ClassName { get; set; }

}

}
