//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
            this.ShopTypePermissionMaps = new HashSet<ShopTypePermissionMap>();
            this.UserGroupPermissionMaps = new HashSet<UserGroupPermissionMap>();
        }
    
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public int Parent { get; set; }
        public int OverrideParent { get; set; }
        public int Position { get; set; }
        public string Type { get; set; }
        public string PermissionGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTypePermissionMap> ShopTypePermissionMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroupPermissionMap> UserGroupPermissionMaps { get; set; }
    }
}
