//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostCode
    {
        public int PostCodeId { get; set; }
        public int DistrictId { get; set; }
        public string PostCode1 { get; set; }
        public string Remark { get; set; }
    }
}
