//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStageGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStageGroup()
        {
            this.BrandFeatureProducts = new HashSet<BrandFeatureProduct>();
            this.GlobalCatFeatureProducts = new HashSet<GlobalCatFeatureProduct>();
            this.LocalCatFeatureProducts = new HashSet<LocalCatFeatureProduct>();
            this.ProductStages = new HashSet<ProductStage>();
            this.ProductStageGlobalCatMaps = new HashSet<ProductStageGlobalCatMap>();
            this.ProductStageRelateds = new HashSet<ProductStageRelated>();
            this.ProductStageRelateds1 = new HashSet<ProductStageRelated>();
            this.ProductStageTags = new HashSet<ProductStageTag>();
            this.ProductStageLocalCatMaps = new HashSet<ProductStageLocalCatMap>();
        }
    
        public long ProductId { get; set; }
        public int ShopId { get; set; }
        public int GlobalCatId { get; set; }
        public Nullable<int> LocalCatId { get; set; }
        public Nullable<int> AttributeSetId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public int TheOneCardEarn { get; set; }
        public string GiftWrap { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public bool ControlFlag1 { get; set; }
        public bool ControlFlag2 { get; set; }
        public bool ControlFlag3 { get; set; }
        public string Remark { get; set; }
        public bool InfoFlag { get; set; }
        public bool ImageFlag { get; set; }
        public bool OnlineFlag { get; set; }
        public string InformationTabStatus { get; set; }
        public string ImageTabStatus { get; set; }
        public string CategoryTabStatus { get; set; }
        public string VariantTabStatus { get; set; }
        public string MoreOptionTabStatus { get; set; }
        public string RejectReason { get; set; }
        public bool Visibility { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual AttributeSet AttributeSet { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandFeatureProduct> BrandFeatureProducts { get; set; }
        public virtual GlobalCategory GlobalCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalCatFeatureProduct> GlobalCatFeatureProducts { get; set; }
        public virtual LocalCategory LocalCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalCatFeatureProduct> LocalCatFeatureProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStage> ProductStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageGlobalCatMap> ProductStageGlobalCatMaps { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageRelated> ProductStageRelateds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageRelated> ProductStageRelateds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageTag> ProductStageTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageLocalCatMap> ProductStageLocalCatMaps { get; set; }
    }
}
