//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStageGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStageGroup()
        {
            this.BrandFeatureProducts = new HashSet<BrandFeatureProduct>();
            this.GlobalCatFeatureProducts = new HashSet<GlobalCatFeatureProduct>();
            this.LocalCatFeatureProducts = new HashSet<LocalCatFeatureProduct>();
            this.ProductHistoryRelateds = new HashSet<ProductHistoryRelated>();
            this.ProductHistoryRelateds1 = new HashSet<ProductHistoryRelated>();
            this.ProductRelateds = new HashSet<ProductRelated>();
            this.ProductRelateds1 = new HashSet<ProductRelated>();
            this.ProductStageGlobalCatMaps = new HashSet<ProductStageGlobalCatMap>();
            this.ProductStageRelateds = new HashSet<ProductStageRelated>();
            this.ProductStageRelateds1 = new HashSet<ProductStageRelated>();
            this.ProductStageTags = new HashSet<ProductStageTag>();
            this.ProductStageLocalCatMaps = new HashSet<ProductStageLocalCatMap>();
            this.ProductStages = new HashSet<ProductStage>();
        }
    
        public long ProductId { get; set; }
        public int ShopId { get; set; }
        public int GlobalCatId { get; set; }
        public Nullable<int> LocalCatId { get; set; }
        public Nullable<int> AttributeSetId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public int ShippingId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public Nullable<System.DateTime> NewArrivalDate { get; set; }
        public int TheOneCardEarn { get; set; }
        public string GiftWrap { get; set; }
        public bool IsNew { get; set; }
        public bool IsClearance { get; set; }
        public bool IsBestSeller { get; set; }
        public bool IsOnlineExclusive { get; set; }
        public bool IsOnlyAt { get; set; }
        public string Remark { get; set; }
        public bool InfoFlag { get; set; }
        public bool ImageFlag { get; set; }
        public bool OnlineFlag { get; set; }
        public string InformationTabStatus { get; set; }
        public string ImageTabStatus { get; set; }
        public string CategoryTabStatus { get; set; }
        public string VariantTabStatus { get; set; }
        public string MoreOptionTabStatus { get; set; }
        public string RejectReason { get; set; }
        public string Status { get; set; }
        public string FirstApproveBy { get; set; }
        public Nullable<System.DateTime> FirstApproveOn { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveOn { get; set; }
        public string RejecteBy { get; set; }
        public Nullable<System.DateTime> RejectOn { get; set; }
        public string SubmitBy { get; set; }
        public Nullable<System.DateTime> SubmitOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public Nullable<int> OldGroupId { get; set; }
    
        public virtual AttributeSet AttributeSet { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandFeatureProduct> BrandFeatureProducts { get; set; }
        public virtual GlobalCategory GlobalCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GlobalCatFeatureProduct> GlobalCatFeatureProducts { get; set; }
        public virtual LocalCategory LocalCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalCatFeatureProduct> LocalCatFeatureProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHistoryRelated> ProductHistoryRelateds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHistoryRelated> ProductHistoryRelateds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRelated> ProductRelateds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRelated> ProductRelateds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageGlobalCatMap> ProductStageGlobalCatMaps { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageRelated> ProductStageRelateds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageRelated> ProductStageRelateds1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageTag> ProductStageTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStageLocalCatMap> ProductStageLocalCatMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStage> ProductStages { get; set; }
    }
}
