//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStageRelated
    {
        public long Parent { get; set; }
        public long Child { get; set; }
        public int ShopId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual ProductStageGroup ProductStageGroup { get; set; }
        public virtual ProductStageGroup ProductStageGroup1 { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
