//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStageVariant
    {
        public int VariantId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Attribute1Id { get; set; }
        public Nullable<int> Attribute2Id { get; set; }
        public string ValueEn1 { get; set; }
        public string ValueTh1 { get; set; }
        public string ValueEn2 { get; set; }
        public string ValueTh2 { get; set; }
        public string ProductNameEn { get; set; }
        public string ProductNameTh { get; set; }
        public string Pid { get; set; }
        public int ShopId { get; set; }
        public string Sku { get; set; }
        public string Upc { get; set; }
        public string Display { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string DescriptionFullEn { get; set; }
        public string DescriptionShortEn { get; set; }
        public string DescriptionFullTh { get; set; }
        public string DescriptionShortTh { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> SaftyStock { get; set; }
        public string VideoLink { get; set; }
        public string ShippingMethod { get; set; }
        public decimal Length { get; set; }
        public decimal Height { get; set; }
        public decimal Width { get; set; }
        public string DimensionUnit { get; set; }
        public decimal Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<bool> DefaultVaraint { get; set; }
        public bool Visibility { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Attribute Attribute1 { get; set; }
        public virtual ProductStage ProductStage { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
