//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;

    public partial class ProductStageRelated
    {
        public long Parent { get; set; }
        public long Child { get; set; }
        public int ShopId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual ProductStageGroup ProductStageGroup { get; set; }
        public virtual ProductStageGroup ProductStageGroup1 { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
