//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionBuy1Get1Item
    {
        public int PromotionBuy1Get1ItemId { get; set; }
        public string NameEN { get; set; }
        public string NameTH { get; set; }
        public string URLKey { get; set; }
        public Nullable<int> PIDBuy { get; set; }
        public Nullable<int> PIDGet { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionCodeRef { get; set; }
        public string CampaignID { get; set; }
        public string CampaignName { get; set; }
        public Nullable<int> MarketingAbsorb { get; set; }
        public Nullable<int> MerchandiseAbsorb { get; set; }
        public Nullable<int> VendorAbsorb { get; set; }
        public string ShortDescriptionTH { get; set; }
        public string LongDescriptionTH { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string LongDescriptionEN { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.TimeSpan> EffectiveTime { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.TimeSpan> ExpiryTime { get; set; }
        public string ProductBoxBadge { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string CreateIP { get; set; }
        public string UpdateIP { get; set; }
        public Nullable<int> CMSStatusFlowId { get; set; }
    }
}
