//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionT1C
    {
        public int TOneCId { get; set; }
        public decimal Rate { get; set; }
        public int MaxPoint { get; set; }
        public int StartPoint { get; set; }
        public string Day { get; set; }
        public bool IsEveryDay { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    }
}
