//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionOnTopCreditCard
    {
        public int OnTopCreditCardId { get; set; }
        public string NameEN { get; set; }
        public string NameTH { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.TimeSpan> EffectiveTime { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.TimeSpan> ExpiryTime { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string PaymantId { get; set; }
        public string ShortDescriptionTH { get; set; }
        public string ShortDescriptionEN { get; set; }
        public string DiscountType { get; set; }
        public Nullable<bool> FreeShipping { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<decimal> MinimumOrderAmount { get; set; }
        public Nullable<decimal> MaximumDiscountAmount { get; set; }
        public string IconURLTH { get; set; }
        public string IconURLEN { get; set; }
        public string BankNameEN { get; set; }
        public string BankNameTH { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateIP { get; set; }
        public string UpdateIP { get; set; }
    }
}
