//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLog
    {
        public int ReportLogId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateBy { get; set; }
        public string CreatedIP { get; set; }
    }
}
