
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Colsp.Entity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StoreReceive
{

    public string InvNo { get; set; }

    public string WebOrderId { get; set; }

    public string SoNo { get; set; }

    public string CustId { get; set; }

    public string CustName { get; set; }

    public string CustEmail { get; set; }

    public int NumOfBox { get; set; }

    public int NumOfBag { get; set; }

    public int NumOfStar { get; set; }

    public System.DateTime StoreReceiveDate { get; set; }

    public string StoreReceiveBy { get; set; }

    public Nullable<System.DateTime> CustReceiveDate { get; set; }

    public string CustReceiveBy { get; set; }

    public string Remark { get; set; }

    public int Status { get; set; }

    public string BranchCode { get; set; }

    public System.DateTime CreateOn { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public string UpdateBy { get; set; }

    public bool IsSendMail { get; set; }

    public bool IsSendRemind { get; set; }

    public Nullable<System.DateTime> ResendDate { get; set; }

    public string ReturnNo { get; set; }

    public string MobileNoReceiveCode { get; set; }

}

}
