//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreReturn
    {
        public string ReturnNo { get; set; }
        public Nullable<System.DateTime> InformDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int ReturnType { get; set; }
        public string InvNo { get; set; }
        public string WebOrderId { get; set; }
        public string SoNo { get; set; }
        public string CustId { get; set; }
        public string CustName { get; set; }
        public int ReasonId { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public bool IsPrint { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string UpdateBy { get; set; }
    }
}
