//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCMCity
    {
        public string ProvinceID { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public System.DateTime CreateOn { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string UpdateBy { get; set; }
        public string Postcode { get; set; }
        public string Remark { get; set; }
    }
}
