//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBRoleTmp
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string AllowIPRange { get; set; }
        public System.DateTime Createon { get; set; }
        public string Createby { get; set; }
    }
}
