//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBSetting
    {
        public string TokenKey { get; set; }
        public System.DateTime TokenKeyExpireDate { get; set; }
        public int T1CStartPoint { get; set; }
        public decimal T1CRate { get; set; }
        public string TokenKeyUAT { get; set; }
    }
}
