//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUserAdminWebTokenTmp
    {
        public string UserId { get; set; }
        public string Token { get; set; }
        public string Browser { get; set; }
        public string UserDevice { get; set; }
        public string Os { get; set; }
        public string WebAgent { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
