
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Colsp.Entity.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBUserAdminTmp
{

    public string UserId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string BranchCode { get; set; }

    public bool IsActive { get; set; }

    public System.DateTime CreateOn { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }

    public string UpdateBy { get; set; }

    public Nullable<System.DateTime> LastActivity { get; set; }

}

}
