//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeComponentMap
    {
        public int ThemeId { get; set; }
        public int ComponentId { get; set; }
        public int Count { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
    
        public virtual Theme Theme { get; set; }
        public virtual ThemeComponent ThemeComponent { get; set; }
    }
}
