//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Api.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_Attribute = new HashSet<Product_Attribute>();
            this.Product_Tag = new HashSet<Product_Tag>();
            this.Product_Variant = new HashSet<Product_Variant>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> global_cat_id { get; set; }
        public Nullable<int> local_cat_id { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> seller_id { get; set; }
        public string brand_name_en { get; set; }
        public string brand_name_th { get; set; }
        public string product_name_en { get; set; }
        public string product_name_th { get; set; }
        public string uid { get; set; }
        public string pid { get; set; }
        public string sku { get; set; }
        public string upc { get; set; }
        public decimal original_price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public string description_full_en { get; set; }
        public string description_short_en { get; set; }
        public string description_full_th { get; set; }
        public string description_short_th { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> safty_stock { get; set; }
        public string shipping_method { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> width { get; set; }
        public string dimenstion_unit { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> dimenstion_weight { get; set; }
        public string meta_title { get; set; }
        public string meta_description { get; set; }
        public string meta_key { get; set; }
        public string url_en { get; set; }
        public string url_th { get; set; }
        public string boost_weight { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<System.TimeSpan> effective_time { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.TimeSpan> expiry_time { get; set; }
        public Nullable<bool> control_flag1 { get; set; }
        public Nullable<bool> control_flag2 { get; set; }
        public Nullable<bool> control_flag3 { get; set; }
        public string remark { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
    
        public virtual Global_Category Global_Category { get; set; }
        public virtual Local_Category Local_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Attribute> Product_Attribute { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Tag> Product_Tag { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Variant> Product_Variant { get; set; }
    }
}
