
using Colsp.Model.Requests;
using System;
using System.Collections.Generic;
using Colsp.Api.Constants;

namespace Colsp.Api.Mockup
{
    public static class OrderMockup
    {
        public static PurchaseOrderReuest O1 = new PurchaseOrderReuest()
        {
            OrderId = "OI0001",
            TrackingNumber = "TR0001",
            ShopId = 27,
            CustomerName = "Laki Sik",
            OrderDate = new DateTime(2016,3,24,1,10,0),
            ShippingType = "Kerry",
            Status = Constant.ORDER_PAYMENT_PENDING,
            BillAddress1 = "This is billing address 1",
            BillAddress2 = "This is billing address 2",
            BillAddress3 = "This is billing address 3",
            BillAddress4 = "This is billing address 4",
            ShipContactor = "Ship Contactor",
            ShipAddress1 = "This is shipping address 1",
            ShipAddress2 = "This is shipping address 2",
            ShipAddress3 = "This is shipping address 3",
            ShipAddress4 = "This is shipping address 4",
            InvoiceAddress1 = "This is invoice address 1",
            InvoiceAddress2 = "This is invoice address 2",
            InvoiceAddress3 = "This is invoice address 3",
            InvoiceAddress4 = "This is invoice address 4",
            ShipAreaCode = "Area Code",
            ShipCity = "This is City",
            ShipDistrict = "This is District",
            ShipProvince = "This is Province",
            OrdDiscAmt = 0,
            TotalAmt = 1000,
            GrandTotalAmt = 1000,
            Products = new List<PurchaseOrderDetailReuest>()
            {
                new PurchaseOrderDetailReuest()
                {
                    ProductId = 572,
                    Pid = "11112L9",
                    ProductNameEn = "ALIVE 5",
                    Quantity = 2,
                    ShipQuantity = 2,
                    UnitPrice = 250
                },
                new PurchaseOrderDetailReuest()
                {
                    ProductId = 68,
                    Pid = "11112L8",
                    ProductNameEn = "Test World",
                    Quantity = 1,
                    ShipQuantity = 1,
                    UnitPrice = 500
                }
            }
        };

        public static PurchaseOrderReuest O1_1  = new PurchaseOrderReuest() { OrderId = "OI0001_1" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 1 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_2  = new PurchaseOrderReuest() { OrderId = "OI0001_2" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 2 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 2, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_3  = new PurchaseOrderReuest() { OrderId = "OI0001_3" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 3 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 3, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_4  = new PurchaseOrderReuest() { OrderId = "OI0001_4" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 4 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_5  = new PurchaseOrderReuest() { OrderId = "OI0001_5" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 5 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_6  = new PurchaseOrderReuest() { OrderId = "OI0001_6" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 6 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_7  = new PurchaseOrderReuest() { OrderId = "OI0001_7" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 7 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 3, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_8  = new PurchaseOrderReuest() { OrderId = "OI0001_8" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 8 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_9  = new PurchaseOrderReuest() { OrderId = "OI0001_9" , TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 9 , 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 2, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_10 = new PurchaseOrderReuest() { OrderId = "OI0001_10", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 10, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_11 = new PurchaseOrderReuest() { OrderId = "OI0001_11", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 11, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 5, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_12 = new PurchaseOrderReuest() { OrderId = "OI0001_12", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 12, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_13 = new PurchaseOrderReuest() { OrderId = "OI0001_13", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 13, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_14 = new PurchaseOrderReuest() { OrderId = "OI0001_14", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 14, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 9, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_15 = new PurchaseOrderReuest() { OrderId = "OI0001_15", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 15, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O1_16 = new PurchaseOrderReuest() { OrderId = "OI0001_16", TrackingNumber = "TR0001", ShopId = 27, CustomerName = "Laki Sik", OrderDate = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 16, 10, 0), ShippingType = "Kerry", Status = Constant.ORDER_PAYMENT_PENDING, BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { ProductId = 572, Pid = "11112L9", ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { ProductId = 68, Pid = "11112L8", ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };


        public static PurchaseOrderReuest O2 = new PurchaseOrderReuest() { OrderId = "OI0002", TrackingNumber = "TR0002", ShopId = 27,  CustomerName = "Poon", OrderDate = DateTime.Now, ShippingType = "DHL",   Status = Constant.ORDER_PAYMENT_CONFIRM,  BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O3 = new PurchaseOrderReuest() { OrderId = "OI0003", TrackingNumber = "TR0003", ShopId = 27 , CustomerName = "Eart", OrderDate = DateTime.Now, ShippingType = "DHL",   Status = Constant.ORDER_PREPARING ,       BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O4 = new PurchaseOrderReuest() { OrderId = "OI0004", TrackingNumber = "TR0004", ShopId = 27 , CustomerName = "Nat",  OrderDate = DateTime.Now, ShippingType = "DHL",   Status = Constant.ORDER_READY_TO_SHIP ,   BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O5 = new PurchaseOrderReuest() { OrderId = "OI0005", TrackingNumber = "TR0005", ShopId = 27 , CustomerName = "Up",   OrderDate = DateTime.Now, ShippingType = "Kerry", Status = Constant.ORDER_SHIPPING,         BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O6 = new PurchaseOrderReuest() { OrderId = "OI0006", TrackingNumber = "TR0006", ShopId = 27 , CustomerName = "Noon", OrderDate = DateTime.Now, ShippingType = "Kerry", Status = Constant.ORDER_DELIVERED ,       BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };
        public static PurchaseOrderReuest O7 = new PurchaseOrderReuest() { OrderId = "OI0007", TrackingNumber = "TR0007", ShopId = 27 , CustomerName = "Pong", OrderDate = DateTime.Now, ShippingType = "DHL",   Status = Constant.ORDER_CANCELED ,        BillAddress1 = "This is billing address 1", BillAddress2 = "This is billing address 2", BillAddress3 = "This is billing address 3", BillAddress4 = "This is billing address 4", ShipContactor = "Ship Contactor", ShipAddress1 = "This is shipping address 1", ShipAddress2 = "This is shipping address 2", ShipAddress3 = "This is shipping address 3", ShipAddress4 = "This is shipping address 4", InvoiceAddress1 = "This is invoice address 1", InvoiceAddress2 = "This is invoice address 2", InvoiceAddress3 = "This is invoice address 3", InvoiceAddress4 = "This is invoice address 4", ShipAreaCode = "Area Code", ShipCity = "This is City", ShipDistrict = "This is District", ShipProvince = "This is Province", OrdDiscAmt = 0, TotalAmt = 1000, GrandTotalAmt = 1000, Products = new List<PurchaseOrderDetailReuest>() { new PurchaseOrderDetailReuest() { Pid = "11112L9",ProductId = 572, ProductNameEn = "ALIVE 5", Quantity = 2, ShipQuantity = 2, UnitPrice = 250 }, new PurchaseOrderDetailReuest() { Pid = "111119J", ProductId = 68, ProductNameEn = "Test World", Quantity = 1, UnitPrice = 500 } } };

        public static List<PurchaseOrderReuest> OrderList = new List<PurchaseOrderReuest>() {
            O1,O1_1,O1_2,O1_3,O1_4,O1_5,O1_6,O1_7,O1_8,O1_9,O1_10,O1_11,O1_12,O1_13,O1_14,O1_15,O1_16,
            O2,
            O3,
            O4,
            O5,
            O6,
            O7
        };
    }
}