version: 0.0
os: windows
files:
  - source: .\src
    destination: c:\inetpub\wwwroot
  - source: .\scripts\bash
    destination: c:\temp\sp-win\bash
  - source: .\scripts\ps
    destination: c:\temp\sp-win\ps
hooks:
  ApplicationStop:
    - location: scripts\dereg_elb.bat
    - location: scripts\app_stop.bat
  ApplicationStart:
    - location: scripts\app_start.bat
    - location: scripts\reg_elb.bat
