//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Tag
    {
        public int product_id { get; set; }
        public int tag_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
