//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colsp.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Products = new HashSet<Product>();
            this.Shops = new HashSet<Shop>();
            this.User_Group_Map = new HashSet<User_Group_Map>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string pwd_last_chg { get; set; }
        public string email { get; set; }
        public string name_en { get; set; }
        public string name_th { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> login_fail_count { get; set; }
        public Nullable<System.DateTime> last_login_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_dt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Group_Map> User_Group_Map { get; set; }
    }
}
